### PR TITLE
Change to make setting the Time work on vivofit

### PR DESCRIPTION
**Pull request by balu-**

### CODE REVIEW

**Comment by Tigge** [comment]
(See discussion in Tigge/antfs-cli#130)

**Comment by Tigge** [comment]
The failed tests are my fault here, forgot that Python 2 treats `06` as octal values (which doesn't matter here really but should be fixed). Python 3 however uses the `0o06` notation and throws and error for values such as `06` (which is good).

**Comment by Tigge** [comment]
https://github.com/Tigge/openant/commit/911137406852c438c0fdfea35d3eab964f5d511a and https://github.com/Tigge/openant/commit/650696f1d1c8fbb26669b2318d1e36cefbdd89bf are now merged to openant. Thank you!

**Comment by AndreasPapageorgiou** [comment]
Hi Tigge, 

Using ba4c276 on vivofit: even though the time appears to be set, with no issues
```
Authenticating with vívofit 
 - Passkey: OK
 - Set time: OK
```

the time does not change on the actual device. 
Any ideas?
Thanks

**Comment by psukys** [comment]
I've noticed that the firmware for vivofit is constantly updating, thus I guess that might also be a problem in communication with vivofit?

**Comment by Tigge** [comment]
@psukys The standard shouldn't change so I don't think that is the problem. Unfortunately I don't have a Vívofit so I'm unable to test this. @balu- reported some success in <https://github.com/Tigge/antfs-cli/issues/130#issuecomment-89877480>, but it seems it is not working anymore?

If someone could supply a USB log, from a Windows machine (or VM with the same) where setting the time on a Vívofit work, that could help me track down what is going on.

**Comment by psukys** [comment]
@Tigge I've got a Win10 VM, although I'm not familiar with USB logs for Windows. Is there a ready log/program to receive the log/guide to receive the log?

**Comment by Tigge** [comment]
@psukys On a VM you could probably do the logging on the host (Linux) side. I haven't tried it but usbmon and Wireshark should work well: <https://wiki.wireshark.org/CaptureSetup/USB>.

On VMWare there are built in USB logging: <http://esec-lab.sogeti.com/posts/2011/04/06/sniffing-usb-traffic-with-vmware.html>. For VirtualBox I'm not sure, but the first method should work still.

**Comment by psukys** [comment]
Alright, I did logging with Wireshark on a simple sync. Attached the logs in wireshark format (and plaintext too)
[simple sync.txt](https://github.com/Tigge/openant/files/202079/simple.sync.txt)
[simple sync.pcapng.gz](https://github.com/Tigge/openant/files/202081/simple.sync.pcapng.gz)

**Pull request closed without merging**
