### PR TITLE
Bring to 1.0.0, ANT+ devices, typing and general bring up to date

### PR DESCRIPTION
**Pull request by tuna-f1sh**
This is less of a PR since it's huge and more of a question of whether this module is open to new maintainers since it looks like you're not actively developing any more? 

I've been using this off and on but recently made a push to get things in order with what I think are some good quality of life and module benefits - see README in changes.

It would be good to update the PyPi package since this seems to have gone largely dormant. Otherwise I will probably create a new package for the fork.

### CODE REVIEW

**Comment by tuna-f1sh** [comment]
I'll use the silence as indication to keep the fork separate rather than maintaining repository - no problem. 

I noticed there was no PyPi package before and so have taken the liberty to create one with my fork: https://pypi.org/project/openant/ . I hope this is also ok, otherwise I'll have to find another name. The original author and repository is still credited there.

**Comment by Tigge** [comment]
Hi! Sorry for the non-responsiveness. It would be nice with new or additional maintainers for this project. I'll look through everything next week.

I think it is a good idea to clean up some things and release a 1.0.0. PyPi is a nice addition as well!

**Comment by firefly-cpp** [comment]
@tuna-f1sh, Thanks for improving this software. Please enable an issue tracker for your fork if there is a chance.

**Comment by Tigge** [comment]
@tuna-f1sh I've looked through everything, and overall they are very very welcome changes. One could discuss if the command line tools and the InfluxDB should be part of the core packages here or reside in a separate project, but those are smaller details.

I've added you as a collaborator. If you are still interested, I'll put you as a maintainer. If you want some sort of speedier contact as well, feel free to email me anytime at <gustav@tiger.name>.

**Comment by tuna-f1sh** [comment]
Yes the CLI tools and InfluxDB are perhaps beyond scope and could be in a 'openant-tools' module. I think since the dependency is optional it is OK for now though. 

I'm sorry but I was too slow to accept the maintainer invite and it has now expired (who knew!). I'm happy to accept however and I will merge this, correcting the README so it no longer mentions it as a fork and point the PyPi package here. I was putting it off as I will also go through trying to act on some of the open issues - quite a lot could be closed/updated on this. I also plan to upload the basic readthedocs.io that can be expanded on.

**Pull request merged**
